version: '3'

services:

  producer-consumer:
    container_name: producer-consumer
    image: producer-consumer
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ../../:/app
      - ./storage:/app/storage
    expose:
      - "8080"
    depends_on:
      - producer-consumer-db
    restart: always
    environment:
      APP_PORT: 8080
      SPRING_APPLICATION_JSON: '{"spring": {"datasource": {"url": "jdbc:mysql://producer-consumer-db:3306/counter", "username": "root", "password": "root"}}}'
    command: "mvn clean spring-boot:run"
    networks:
      - al-net

  producer-consumer-db:
    container_name: producer-consumer-db
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./devops/mysql/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: counter
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - al-net

networks:
  al-net:
    external:
      name: al-net-shared


